use mifid;
DROP TABLE CFI_ASSETCLASS_MAP;
CREATE TABLE CFI_ASSETCLASS_MAP (
    ENTRY_ID INT NOT NULL AUTO_INCREMENT primary key,
    CFI_GROUP VARCHAR(10),
    CFI_CATEGORY_DESC VARCHAR(255),
    CFI_GROUP_DESC VARCHAR(255),
    ASSET_CLASS_ID VARCHAR(255),
    ASSET_CLASS_DESC VARCHAR(255),
    ENTRY_TIMESTAMP timestamp default CURRENT_TIMESTAMP()
);