use mifid;
DROP TABLE MIFID_RTS27_TABLE1;
CREATE TABLE MIFID_RTS27_TABLE1 (
    ENTRY_ID INT NOT NULL AUTO_INCREMENT primary key,
    SOURCE_COMPANY_GROUP_NAME VARCHAR(255),
    SOURCE_COMPANY_NAME VARCHAR(255),
    SOURCE_COMPANY_CODE VARCHAR(100),
    COUNTRY_OF_COMPETENT_AUTHORITY varchar (50),
    MARKET_SEGMENT_NAME varchar(255),
    MARKET_SEGMENT_ID varchar(10),
    TRADE_DATE date,
    OUTAGES_NATURE varchar(100),
    OUTAGES_NUMBER int,
    OUTAGES_AVERAGE_DURATION varchar(100),
    SCHEDULED_AUCTION_NATURE varchar(100),
    SCHEDULED_AUCTION_NUMBER varchar(100),
    SCHEDULED_AUCTION_AVERAGE_DURATION varchar(100),
    FAILED_TRANSACTIONS_NUMBER int,
    FAILED_TRANSACTIONS_PERCENT decimal (4,2),
    FILENAME VARCHAR(255),
    FILE_ID varchar(255),
    ISIN varchar(255),
    VENUE varchar(255),
    INSTRUMENT_NAME varchar(255),
    INSTRUMENT_CLASSIFICATION varchar(255),
    CURRENCY varchar(255),
    ENTRY_TIMESTAMP timestamp default CURRENT_TIMESTAMP()
);
