use mifid;
CREATE INDEX table2_index1
ON MIFID_RTS27_TABLE2 (SOURCE_COMPANY_NAME, ISIN, TRADE_DATE);

use mifid;
CREATE INDEX table4_index1
ON MIFID_RTS27_TABLE4 (SOURCE_COMPANY_NAME, ISIN, TRADE_DATE);

use mifid;
CREATE INDEX table6_index1
ON MIFID_RTS27_TABLE6 (SOURCE_COMPANY_NAME, ISIN, TRADE_DATE);

use mifid;
CREATE INDEX table1_index2
ON MIFID_RTS27_TABLE1 (FILE_ID);

use mifid;
CREATE INDEX table2_index2
ON MIFID_RTS27_TABLE2 (FILE_ID);

use mifid;
CREATE INDEX table4_index2
ON MIFID_RTS27_TABLE4 (FILE_ID);

use mifid;
CREATE INDEX table6_index2
ON MIFID_RTS27_TABLE6 (FILE_ID);

--
-- INDEX ON MIFID_FIRDS table on ISIN
use mifid;
CREATE INDEX MIFID_FIRDS_ISIN
ON MIFID_FIRDS (INSTRUMENT_IDENTIFICATION_CODE);

--
-- INDEX ON MIFID_FIRDS table on TRADING_VENUE
use mifid;
CREATE INDEX MIFID_FIRDS_VENUE
ON MIFID_FIRDS (trading_venue);

--
-- INDEX ON MIFID_FIRDS table on ENTRY_ID
use mifid;
CREATE INDEX MIFID_FIRDS_ENTRY_ID
ON MIFID_FIRDS (ENTRY_ID);

--
-- INDEX ON MIFID_FIRDS table on ISIN, ENTRY_ID, VENUE
use mifid;
drop INDEX MIFID_FIRDS_ISIN_VENUE;
CREATE INDEX MIFID_FIRDS_ISIN_ENTRYID_VENUE
ON MIFID_FIRDS (INSTRUMENT_IDENTIFICATION_CODE,ENTRY_ID, TRADING_VENUE);

--
-- INDEX ON MIFID_FIRDS table on ISIN, ENTRY_ID
use mifid;
CREATE INDEX MIFID_FIRDS_ISIN_ENTRYID
ON MIFID_FIRDS (INSTRUMENT_IDENTIFICATION_CODE,ENTRY_ID);

--
-- INDEX ON MIFID_FIRDS table on ISIN
use mifid;
CREATE INDEX UNIQUE_FIRDS_ISIN2_ISIN
ON UNIQUE_FIRDS_ISIN2 (ISIN);



