use mifid;
DROP TABLE CFI_CHAR_MAP;
CREATE TABLE CFI_CHAR_MAP (
    ENTRY_ID INT NOT NULL AUTO_INCREMENT primary key,
    CFI_GROUP varchar(10),
    CFI_ATTRIBUTE_POSITION varchar(10),
    CFI_ATTRIBUTE_GROUP_DESC varchar(200),
    CFI_ATTRIBUTE varchar(1),
    CFI_ATTRIBUTE_DESC varchar(200),
    ENTRY_TIMESTAMP timestamp default CURRENT_TIMESTAMP()
);