use mifid;
CREATE INDEX table2_index1
ON MIFID_RTS27_TABLE2 (SOURCE_COMPANY_NAME, ISIN, TRADE_DATE);

use mifid;
CREATE INDEX table4_index1
ON MIFID_RTS27_TABLE4 (SOURCE_COMPANY_NAME, ISIN, TRADE_DATE);

use mifid;
CREATE INDEX table6_index1
ON MIFID_RTS27_TABLE6 (SOURCE_COMPANY_NAME, ISIN, TRADE_DATE);

use mifid;
CREATE INDEX table1_index2
ON MIFID_RTS27_TABLE1 (FILE_ID);

use mifid;
CREATE INDEX table2_index2
ON MIFID_RTS27_TABLE2 (FILE_ID);

use mifid;
CREATE INDEX table4_index2
ON MIFID_RTS27_TABLE4 (FILE_ID);

use mifid;
CREATE INDEX table6_index2
ON MIFID_RTS27_TABLE6 (FILE_ID);

