use mifid;
DROP TABLE MIFID_RTS27_TABLE2;
CREATE TABLE MIFID_RTS27_TABLE2 (
    ENTRY_ID INT NOT NULL AUTO_INCREMENT primary key,
    SOURCE_COMPANY_NAME VARCHAR(255),
    FILENAME VARCHAR(255),
    FILE_ID varchar(255),
    ISIN varchar(255),
    TRADE_DATE date,
    VENUE varchar(255),
    INSTRUMENT_NAME varchar(255),
    INSTRUMENT_CLASSIFICATION varchar(255),
    CURRENCY varchar(255),
    ENTRY_TIMESTAMP timestamp default CURRENT_TIMESTAMP()
);

use mifid;
ALTER TABLE MIFID_RTS27_TABLE2 add column ASSET_CLASS_ID int;
ALTER TABLE MIFID_RTS27_TABLE2 add column ASSET_CLASS_DESC VARCHAR(100);
ALTER TABLE MIFID_RTS27_TABLE2 add column CFI_ATTR_1_DESC VARCHAR(100);
ALTER TABLE MIFID_RTS27_TABLE2 add column CFI_ATTR_2_DESC VARCHAR(100);
ALTER TABLE MIFID_RTS27_TABLE2 add column CFI_ATTR_3_DESC VARCHAR(100);
ALTER TABLE MIFID_RTS27_TABLE2 add column CFI_ATTR_4_DESC VARCHAR(100);
ALTER TABLE MIFID_RTS27_TABLE2 add column CFI_ATTR_5_DESC VARCHAR(100);
ALTER TABLE MIFID_RTS27_TABLE2 add column CFI_ATTR_6_DESC VARCHAR(100);

ALTER TABLE MIFID_RTS27_TABLE2 add column INSTRUMENT_CCY1 VARCHAR(5);
ALTER TABLE MIFID_RTS27_TABLE2 add column INSTRUMENT_CCY2 VARCHAR(5);
ALTER TABLE MIFID_RTS27_TABLE2 add column CCY_PAIR VARCHAR(10);
ALTER TABLE MIFID_RTS27_TABLE2 add column VALUE_DATE date;
ALTER TABLE MIFID_RTS27_TABLE2 add column TENOR VARCHAR(50);



