use mifid;
DROP TABLE MIFID_RTS27_TABLE4;
CREATE TABLE MIFID_RTS27_TABLE4 (
    ENTRY_ID INT NOT NULL AUTO_INCREMENT primary key,
    SOURCE_COMPANY_NAME VARCHAR(255),
    FILENAME VARCHAR(255),
    FILE_ID varchar(255),
    ISIN varchar(255),
    TRADE_DATE date,
    INSTRUMENT_NAME varchar(255),
    SIMPLE_AVERAGE_TRANSACTION_PRICE decimal(20,8),
    VOLUME_WEIGHTED_TRANSACTION_PRICE decimal(20,8),
    HIGHEST_EXECUTED_PRICE decimal (20,8),
    LOWEST_EXECUTED_PRICE decimal (20,8),
    CURRENCY varchar(255),
    ENTRY_TIMESTAMP timestamp default CURRENT_TIMESTAMP()
);