use mifid;
DROP TABLE MIFID_FIRDS;
CREATE TABLE MIFID_FIRDS (
    ENTRY_ID INT NOT NULL AUTO_INCREMENT primary key,
    INSTRUMENT_IDENTIFICATION_CODE VARCHAR(255),
    INSTRUMENT_FULL_NAME VARCHAR(500),
    INSTRUMENT_CLASSIFICATION VARCHAR(255),
    ISSUER_IDENTIFIER varchar (255),
    TRADING_VENUE varchar(255),
    INSTRUMENT_SHORT_NAME varchar(500),
    TERMINATION_DATE date default null,
    NOTIONAL_CURRENCY1 varchar(100),
    EXPIRY_DATE date default null,
    DELIVERY_TYPE varchar(100),
    FX_TYPE varchar(100),
    UNDERLYING_ISIN varchar(100),
    OPTION_TYPE varchar(100),
    STRIKE_PRICE_AMT decimal(20,10),
    OPTION_EXERCISE_STYLE varchar(100),
    RELEVANT_COMPETENT_AUTHORITY VARCHAR(255),
    DEBT_TOTAL_ISSUED_NOMINAL_AMOUNT int,
    DEBT_MATURTY_DATE date default null,
    DEBT_FIXED_RATE varchar(100),
    FR_DATE date default null,
    FILE_NAME varchar(255),
    ENTRY_TIMESTAMP timestamp default CURRENT_TIMESTAMP()
);